### ISSUE TITLE
Unclear on usage or target audience

### ISSUE THREAD

**Issue by mbbroberg** [basho-labs/riak-clients-vagrant#1]
Hey @christophermancini - this project looks interesting, though I've heard it's confusing to understand what it does and for whom. Could we either (a) clarify its goal and how it gets there in the README or (b) make it private? I'd prefer the former but understand the latter is okay sometimes too.

**Comment by christophermancini** [comment]
Updated the README. Let me know if that is better.

**Comment by mbbroberg** [comment]
Thanks @christophermancini - makes way more sense :ok_hand:. I'll add this to the [meta](https://github.com/basho-labs/vagrant-riak-meta) now!
